markdown: rdiscount
pygments: true
plugins: ./_plugins
safe: false

title: zeroq的小作坊
url: http://zeroq.me
feed: /atom.xml
author:
    name: zeroq
    email: qicfan@gmail.com
    twitter: twitter.com/qicfan
description: zeroq的小作坊